### ISSUE TITLE
Help to send RTS commands

### ISSUE THREAD

**Issue by vaguiner7** [cpainchaud/RFLink32#108]
Hi there, I am using a Sonoff RF BridgeR2 that I did the necessary changes following the [guide](https://github.com/cpainchaud/RFLink32/blob/master/doc/sonoff_rf_bridge.md)

My issue is, I can decode the commands sent from my [SCE-R1](https://www.tube-motors.com/worldwide/Item/4/165) control but I cannot send it from the Sonoff Bridge.

The tests:

01 - Sending the command STOP from my SCE-R1 control I got the results (worked):

- Serial port on the Sonoff

![controll_stop_command_sonoff](https://github.com/cpainchaud/RFLink32/assets/10762632/6ff09842-b711-4399-8283-c06c19e1630e)

- [433_rtl](https://github.com/merbanan/rtl_433) with [820T2 SDR](https://pt.aliexpress.com/item/1005006467185080.html)

![433](https://github.com/cpainchaud/RFLink32/assets/10762632/8712888f-5071-468a-9be2-9ec54ead22a4)

02 - So I used the examples on the [RTS plugin code](https://github.com/cpainchaud/RFLink32/blob/master/RFLink/Plugins/Plugin_017.c) to register a new control on the Sonoff.

![sonoff_rtsshow](https://github.com/cpainchaud/RFLink32/assets/10762632/0e754d07-2841-4507-8097-92ee17ae17a3)

And I tried to send an UP command, but could not see the command on 433_rtl like when I sent from the SCE-R1 control.

![up_command](https://github.com/cpainchaud/RFLink32/assets/10762632/0a36b3f6-056e-4689-a927-6c0e92aa17f7)

To make sure that some signal was  sent I used the [URH ](https://github.com/jopohl/urh)tool to see the spectrum, and I got something.

![Imagem do WhatsApp de 2024-01-26 à(s) 10 11 29_052d36b0](https://github.com/cpainchaud/RFLink32/assets/10762632/7cdc49c1-154c-4a88-bc1b-cbf0b5304531)

My conclusions so far is, the sonoff can send the signal, but the signal is not recognized as a Sonfy-RTS signal.

Do you guys have an idea that can help me? I am not sure if what I did to configure was correct.

Thank you

**Comment by vaidas911** [comment]
Somfy uses different frequency. Use CC1101 and some esp32 and https://github.com/rstrouse/ESPSomfy-RTS

**Comment by vaguiner7** [comment]
It worked pretty well, thanks a lot @vaidas911
