### ISSUE TITLE
D1-Mini RFDEBUG craches

### ISSUE THREAD

**Issue by Niiccoo** [cpainchaud/RFLink32#46]
After using 10;RFDEBUG=ON; the following code crashed the program (in Plugin_001.c):

      RFLink::sendRawPrint(PSTR(";RSSI="));

fix:
 // Replaced PSTR(";RSSI=") with F(";RSSI=")
      RFLink::sendRawPrint(F(";RSSI="));

Probably on all places where combination RFLink::sendRawPrint() and PSTR() is used it will crashes the code.

**Comment by cpainchaud** [comment]
Hi !
You should have submitted a PR !!! :) I will have a look and fix those thank you!
