### ISSUE TITLE
Default user/pass for captive portal?

### ISSUE THREAD

**Issue by omygolly** [cpainchaud/RFLink32#50]
Hi,

Figured I'd give this a try and after downloading and flashing a release an RFLink-AP pops up. But when I try to access 192.168.4.1 a default popup appears asking for admin/pass. I can't for the life of me find the default values for these in any documentation.. :)

**Comment by hvorragend** [comment]
Same problem here, but I've found it:

```
#define RFLINK_WEBUI_DEFAULT_USER "rflink32"
#define RFLINK_WEBUI_DEFAULT_PASSWORD "433mhz"
```

**Comment by cpainchaud** [comment]
thx for replying @omygolly
