### ISSUE TITLE
NewKaku (Plugin_004.c) transmission issue (switch/unit)

### ISSUE THREAD

**Issue by EdnEddy** [cpainchaud/RFLink32#51]
Hi, 

Big thanks @ all of you who made this possible.

There seems to be a switch/index problem with the transmission of NewKaku.

when I receive for example
`20;89;NewKaku;ID=00f0ac76;SWITCH=1;CMD=ON;`

I need to send the following to switch the plug
`10;NewKaku;00f0ac76;0;ON;`

1->0 , 2->1 , 3->2 and so on.

in Plugin_004.c I have changed
`bitstream |= Switch_bitstream; // Complete transmitted address`
to
`bitstream |= Switch_bitstream-1;`

it fixes the problem, but I do not know if there are side effects ;)

and since I have very poor programming skills, 
I would be extremely happy about an integration of **Kaku Transmit PLUGIN_TX_003** 
(tried commenting out `#define PLUGIN_TX_003` and some other changes without success).

**Comment by cpainchaud** [comment]
Hello,

 I believe #95 has fixed your issue. 
 
 Thank you
