### ISSUE TITLE
index.html.gz.h no such file or directory

### ISSUE THREAD

**Issue by Marc1200** [cpainchaud/RFLink32#56]
Hello, 

i am trying to upload the code but the compiler cannot find the index.html.gz.h file.
can someone provide this file?

**Comment by cpainchaud** [comment]
Hi,
It's provided by platformio dependency mananger. 

You can get it manually from https://github.com/cpainchaud/rflink-webui

**Comment by cpainchaud** [comment]
https://github.com/cpainchaud/rflink-webui/tree/main/cpp

**Comment by Marc1200** [comment]
Okay, thanks
