### ISSUE TITLE
Request: Address for MQTT Server

### ISSUE THREAD

**Issue by elodur** [cpainchaud/RFLink32#60]
For the MQTT server-address only an IP is accepted. It would be great to be able to use a name like "mqtt.local".

**Comment by cpainchaud** [comment]
Hi this is making sense!

**Comment by cpainchaud** [comment]
Actually I am curious @elodur  : are you getting any error message?

**Comment by elodur** [comment]
I think it did, like 'invalid IP'. When I try to change it back now, it says 'success' and keeps the IP.

**Comment by cpainchaud** [comment]
I see, the UI is stopping you! I need to fix that.

A workaround you could try is CLI with this command:
10;config;set;{"mqtt":{"server":"MY_SERVER_NAME_HERE"}}

let me know if this is connecting as expected

**Comment by elodur** [comment]
Works fine.

**Comment by cpainchaud** [comment]
I have published changes, it should be fixed in UI as well now
