### ISSUE TITLE
SSL Cert for MQTT connection

### ISSUE THREAD

**Issue by yndtrud** [cpainchaud/RFLink32#62]
Hello! 

Recently used RFLink32. 
I have a Sonoff RF Brdige R2 with a direct hack. Everything works without problems (almost). 

I want to know: for MQTT it is possible to use SSL, but it is not possible to specify a CA certificate in the WebUI. 
In json config (in code) you have a string, and in vue.js you have a switch (type of CA cert).
I thought to fix it, but maybe you did it on purpose? 
Tell me, is this just a bug or a specially disabled feature (for example, due to the size of the certificate)?

**Comment by cpainchaud** [comment]
Hi,  it seems to be a bug, I am going to look into it

**Comment by cpainchaud** [comment]
@yndtrud in the meantime would please try this workaround? run command (preferably from CLI):
`10;config;set;{"mqtt":{"ca_cert":"=====MYCERTHERE====="}}`

**Comment by cpainchaud** [comment]
ok so we have 2 issues: UI and buffer sizes. Out of curiosity how large is your certificate?

**Comment by cpainchaud** [comment]
I have produced a new firmware with a temporary UI fix (because it's ugly right now) and tested on a 8266 device and it's working

**Comment by cpainchaud** [comment]
I found more bugs with ESP8266 architecture, related to NTP (which of course means you cannot validate a certificate). I am working on that ....

**Comment by cpainchaud** [comment]
Can you give a try at this one? https://github.com/cpainchaud/RFLink32/releases/tag/nightly-testing-only

Please clear ca_cert from your config first to save some memory: 
10;config;set;{"mqtt":{"ca_cert":""}}

It's working in my lab ESP8266 so should work for you as well.
