### ISSUE TITLE
Transmitting EV1527

### ISSUE THREAD

**Issue by shubell** [cpainchaud/RFLink32#68]
Hi I am unable to transmit EV1527 signals.
The command: 10;EV1527;000080;0;ON;  
returns 20;36;CMD UNKNOWN

for example 10;Kaku;00004d;1;ON works ok

I use a ESP32.
Anyone else has this issue?

**Comment by shubell** [comment]
It is not implemented

**Comment by protree** [comment]
Did you find a solution? I have the same problem...

**Comment by shubell** [comment]
> Did you find a solution? I have the same problem...

Bought an arduino and used RFLink...  the only other option would be to implement this on my own and the first option was faster
