### ISSUE TITLE
Fix for compile issues with arduino IDE and disabled OTA/portal

### ISSUE THREAD

**Issue by nona00** [cpainchaud/RFLink32#75]
Hello,

thank you very much for the development. I only needed serial transmission for replacing an arduino uno with a wemos d1 mini (ESP8266).

I had serveral issues with compilation with arduino IDE 1.8.1x
1) .ino file was not contained in the git
2) main.cpp was necessary to be removed (otherwise linkage fails)
3) 13_OTA.h and RFLink.cpp did not have a selection for RFLINK_PORTAL_DISABLED
4) ARDUINOJSON_USE_LONG_LONG 1 had to be added to RFLink.h to solve compile issue with ArduinoJSON 6.18.5. Compiliation with 6.21.1 fails
5) some plugins had include paths

attached is a patch with my modifications

[Arduino_IDE.patch](https://github.com/cpainchaud/RFLink32/files/11178506/Arduino_IDE.patch)

**Comment by cpainchaud** [comment]
Hello and thank you,

 This project is not meant to be compiled with Arduino IDE because their IDE lacks quite a few modern features (may be latest Arduino has improved, I don't know but the fact than the entry point has to be an INO file is already a blocker by itself...)
