### ISSUE TITLE
What username and password in 192.168.4.1

### ISSUE THREAD

**Issue by mohapxuct** [cpainchaud/RFLink32#80]
Tell me your login and password, I didn’t find this data in the instructions, the access point rises, but it requires login information by ip.

**Comment by cpainchaud** [comment]
Hi,

From project main page:

Default Login Details
rflink32 / 433mhz

**Comment by JacquesdeBruyn** [comment]
Might want to attach that to the main readme

**Comment by cpainchaud** [comment]
It is there already :)  in Additional Infos section

**Comment by JacquesdeBruyn** [comment]
Ah, I see...need to go get my eyes checked :D
